Project page
HackYourFuture-CPH/class-25-lothbrok pull request #13
Opened 2023-09-27 18:58 UTC by KristinaGru

Add Project Task List View, with possibility to add new task with a title, change tasks completed status with a checkbox and drag and drop tasks to a different list, or to reorder in the same list. Using mock data.

2023-09-28 17:45 UTC, kralle333 commented
Hi I see you have a conflicting file with dev. Can you merge dev into your branch and resolve the conflict?

2023-09-28 19:48 UTC, kralle333 requested changes
All in all, great job!

I have some smaller comments that will help make the code easier to modify in the future and easier to read.

@YurijPaharev Wanna have a look to see if my comments are sensible or if I missed something important?

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +      }
Use a switch case here instead. Also create constants for these different `droppableId`s
Something like:
`
const droppableIdDocumentation = 'documentation'
const droppableIdOngoing = 'ongoing'
so on...
`

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +  const [doneEditing, setDoneEditing] = useState<boolean>(false);
Here is a lot of repetition, you can probably abstract this away in an object. Let's say you have an object representing a Category, that can have:
- An array of tasks
- A description
- Editing status

Abstracting it in this way will then also make it possible to remove/add categories as well open up for the ability for the user to create their own categories.

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +    setDone(filterTaskByStatus('done'));
Same as the comment I made elsewhere, make these values into constant and use them instead of raw string values.

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +              onChange={(e) => setDocumentationDescription(e.target.value)}
When you have created the category object you should be able to loop over your category types to reduce the repetition here.

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/firebase_config.js
> +export const auth = getAuth(app);
I assume it is some formatter that are responsible for these changes?

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/pages/projectView/ProjectView.tsx
> +};
I assume these objects are going to be used elsewhere, maybe it is better to extract them out into their own files

2023-09-28 19:48 UTC, kralle333 commented on frontend/src/pages/projectView/ProjectView.tsx
> +      setProject(projects.filter((project) => project.id === +id)[0]);
how should it act when there is no project?

2023-09-28 19:58 UTC, KristinaGru commented
Thanks for the review Kristian! I'm on it 🙌

2023-09-29 09:46 UTC, YurijPaharev commented
@kralle333 You did an amazing and a very thorough job, I wouldn't have done better myself

2023-09-30 15:19 UTC, kralle333 requested changes
Code looks much cleaner, very nice!

Last comments is about the use of a map to store the values of the categories.

2023-09-30 15:19 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +  };
I am not really sure what the reason is for this map...

2023-09-30 15:19 UTC, kralle333 commented on frontend/src/components/projectListView/ProjectListView.tsx
> +                : section}
If you convert your categories map to an array and then have the values be the Title, then it would make this code much simpler

2023-09-30 19:22 UTC, KristinaGru commented
I kept categories in an object instead of an array to have a pair of list titles I use in the UI and a string that matches the task status in the database, hope that's okay. But I switched to an Object.entries loop and removed the redundant ternary operator that way 🤞.

2023-10-01 15:40 UTC, kralle333 approved these changes
Great work :) Keep it up

2023-10-01 16:01 UTC, merged