Bug/frontend auth
HackYourFuture-CPH/class-25-lothbrok pull request #16
Opened 2023-09-28 19:53 UTC by KristinaGru

## Ticket Link: [ID](https://www.meistertask.com/app/task/307KXTtj/fix-bugs-in-frontend-auth-pages)

## 📝 Description

- added redirection logic for logged in/out user
- removed sidebar from authentication pages
- add alerts for errors during authentication
- fix login page submit button being enabled on mounting

## 🎉 Demos

![image](https://github.com/HackYourFuture-CPH/class-25-lothbrok/assets/101867026/ae9b6a39-434b-4426-842b-45c57be1af80)

2023-09-29 19:47 UTC, kralle333 requested changes
Good job :) I only have some smaller comments

2023-09-29 19:47 UTC, kralle333 commented on frontend/src/App.tsx
> +  },
I think after this PR you should make a PR where the formatter + linter is run on the whole codebase. Reviewing PRs where actual changes are mixed in with formatting changes makes it harder to review.

2023-09-29 19:47 UTC, kralle333 commented on frontend/src/pages/signUp/SignUp.tsx
> +      }
This code is duplicated in LoginPage.tsx, can you extract the error handling elsewhere?

2023-09-29 19:47 UTC, kralle333 commented on frontend/src/pages/signUp/SignUp.tsx
> +        setErrorMessage(`Email address '${data.email}' is already in use `);
not a good idea to do comparison on the message like that, if firebase decides to change the returned error your code breaks. There must be a better way to detect the error type.

2023-09-29 19:49 UTC, kralle333 requested changes
Good job :) I only have some smaller comments

2023-09-29 19:49 UTC, kralle333 requested changes
Good job :) I only have some smaller comments

2023-09-29 20:38 UTC, KristinaGru commented
@kralle333 thanks for review! 🙏 Switched to error code instead of error message check. As for changes in App.tsx, it's due to moving all authentication paths out of '/' paths children array, to fix the problem we've had of sidebar and header showing up in auth pages. Dev should be up to date now with all formatting changes 🙌

2023-09-30 15:10 UTC, kralle333 requested changes

2023-09-30 15:10 UTC, kralle333 commented on frontend/src/pages/signUp/SignUp.tsx
> +      if (e.code === 'auth/email-already-in-use') {
Better :) But lets see if we can prevent using raw strings. It should be possible to use the constants here: https://firebase.google.com/docs/reference/js/auth#autherrorcodes

try importing like this:
`import { AuthErrorCodes } from 'firebase/auth'`

And then you should be able to use the constants for comparison:
`AuthErrorCodes.EMAIL_EXISTS`

2023-09-30 18:23 UTC, KristinaGru commented
Thanks for pointing that out! Switched it in the sign-up error check, but for login did not see anything that'd match the error code I want to check against. Found this issue, so will keep an eye on it if anything changes 🤓  https://github.com/firebase/firebase-js-sdk/issues/7661

2023-10-01 12:01 UTC, KristinaGru commented
@kralle333 added a couple lines to solve the problem of unauthorized path showing for a second before being redirected to this PR. Hope it's ok 🤞

2023-10-01 15:42 UTC, kralle333 approved these changes
There is another constant you missed changing, but I won't let it block this PR. Good job!

2023-10-01 15:42 UTC, kralle333 commented on frontend/src/pages/login/LoginPage.tsx
> +      if (e.code === 'auth/invalid-login-credentials') {
You are missing using the constant here too :)

2023-10-01 15:43 UTC, kralle333 commented on frontend/src/pages/login/LoginPage.tsx
> +      if (e.code === 'auth/invalid-login-credentials') {
ah i see you are aware and that its a issue with firebase. Very nice!

2023-10-01 16:24 UTC, merged