Feature/connect project view to backend
HackYourFuture-CPH/class-25-lothbrok pull request #22
Opened 2023-10-06 17:46 UTC by KristinaGru

## Ticket Link: [ID](https://www.meistertask.com/app/task/pTZQAVud/connect-project-task-view-to-database-data)

## 📝 Description

- Switch from using mock data in project task view page to real database
- Added get, post and put request for tasks and get request for projects

## ⚠️ Notes

- Using local DB
- Making a PR to 'get-db-data' branch, because it has the backend setup

## 🎉 Demos

<img width="943" alt="image" src="https://github.com/HackYourFuture-CPH/class-25-lothbrok/assets/101867026/9e2e9375-54c5-4976-8588-5d06e7afefd0">

2023-10-07 08:12 UTC, kralle333 requested changes
I would incur you to wait for the backend feature to get merged in to develop before you make this PR. When it has been merged in, you can make a new feature branch with develop as base and cherry pick these commits or squash merge this branch.

2023-10-07 13:46 UTC, KristinaGru commented
> I would incur you to wait for the backend feature to get merged in to develop before you make this PR. When it has been merged in, you can make a new feature branch with develop as base and cherry pick these commits or squash merge this branch.

Noted! Just for this time, since the 'get-db-data' branch got merged, would it be fine to leave this PR as is, since it switched to dev as base? This branch is up to date with the current dev, and all the commits here are what I would want to merge it

2023-10-08 10:06 UTC, kralle333 approved these changes
Really nice work, I liked that you renamed user_id to user_uid.

I have one small comment, but it is not blocking

2023-10-08 10:06 UTC, kralle333 commented on frontend/src/pages/projectView/ProjectView.tsx
> +      };
maybe you wanna make a constructor for this? Also rename id into project_id

2023-10-08 20:10 UTC, merged