Updating dom when a field gets updated
HackYourFuture-CPH/class-25-lothbrok pull request #39
Opened 2023-10-18 06:07 UTC by arash8877

## Ticket Link: [ID](https://www.meistertask.com/app/task/ID)

## 📝 Description

- [x] Description of work

## ⚠️ Notes

## 🎉 Demos

2023-10-18 14:56 UTC, kralle333 requested changes
I don't really understand what this pr is for, why does the task details body need a function for getting tasks? Is it some hack to make the dom look like you want to?

Also you haven't used the PR template at all like I have asked for before 😅 
<img width="542" alt="image" src="https://github.com/HackYourFuture-CPH/class-25-lothbrok/assets/5738476/0b2fb704-72fb-48c5-abf9-a90643f6849c">

2023-10-18 14:56 UTC, kralle333 commented on frontend/src/components/TaskDetailsBody/TaskDetailsBody.tsx
> +  const [projectUsers, setProjectUsers] = useState([]);
<img width="646" alt="image" src="https://github.com/HackYourFuture-CPH/class-25-lothbrok/assets/5738476/469622a0-598b-45b3-9ae4-84a3ad358987">
some issues to look into

2023-10-18 14:56 UTC, kralle333 commented on frontend/src/components/TaskDetailsBody/TaskDetailsBody.tsx
> +const TaskDetailsBody = ({ task, getAllTasks }: TaskDetailsBodyType) => {
why does the details of a task need a function to get all tasks?

2023-10-18 16:14 UTC, arash8877 commented on frontend/src/components/TaskDetailsBody/TaskDetailsBody.tsx
> +const TaskDetailsBody = ({ task, getAllTasks }: TaskDetailsBodyType) => {
Because whenever user edits a field, I need to get the updated task to be rendered in dom, then I need to get all tasks in useEffect to access to the updated task.

2023-10-18 16:20 UTC, kralle333 commented on frontend/src/components/TaskDetailsBody/TaskDetailsBody.tsx
> +const TaskDetailsBody = ({ task, getAllTasks }: TaskDetailsBodyType) => {
Ok, if that is what the function does, then rename it to that :) So something like updateTasksInDom

2023-10-19 07:04 UTC, kralle333 approved these changes
very nice!

2023-10-19 19:14 UTC, merged