Basic architecture
HackYourFuture-CPH/class-25-lothbrok pull request #4
Opened 2023-09-19 19:21 UTC by arash8877

added page routes to the front.
made folder 'components' include:
header
searchBar
....

2023-09-20 06:36 UTC, YurijPaharev requested changes
Please note that your changes should not be merged, until other PRs are merged now. You have all your colleagues changes in your branch, probably you should have created separate branches and make PRs from them

2023-09-20 06:57 UTC, arash8877 commented
Hej Yurii

Thanks for the feedback.
My PR include codes from other team-mate because I pull Kristina's code in
my branch. And it was a mistake 🙈
I am not sure what I should do?!

Kr
Arash

On Wed, Sep 20, 2023, 08:36 YurijPaharev ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I do not understand the point of this PR, it contains changes of all other
> PRs but states that it is architecture changes. You probably should have
> created PRs just for your commits, because now there are three almost
> identical PRs
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackYourFuture-CPH/class-25-lothbrok/pull/4#pullrequestreview-1634772948>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ56IXATON3LC3SCCJYKU4LX3KFGJANCNFSM6AAAAAA46ZF56M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-20 07:04 UTC, YurijPaharev commented
I would suggest to wait until other PRs would be merged, cause then all those commits would be in dev branch an you will be able to see the changes only of your current branch

2023-09-20 07:11 UTC, arash8877 commented
OK, I will do that. Thanks.
What about my current PR. Do you accept that?

On Wed, Sep 20, 2023, 09:04 YurijPaharev ***@***.***> wrote:

> I would suggest to wait until other PRs would be merged, cause then all
> those commits would be in dev branch an you will be able to see the changes
> only of your current branch
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackYourFuture-CPH/class-25-lothbrok/pull/4#issuecomment-1727093352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ56IXCDXMYKF37WDBB52VDX3KIQDANCNFSM6AAAAAA46ZF56M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-20 07:56 UTC, YurijPaharev commented
I will look at it when it will be updated with other PR, after merging it to dev. So now you should wait until another PR is approved, push latest updates to your branch and then I will review it

2023-09-20 08:06 UTC, arash8877 commented
Oh thank you 😊 so much

On Wed, Sep 20, 2023, 09:56 YurijPaharev ***@***.***> wrote:

> I will look at it when it will be updated with other PR, after merging it
> to dev. So now you should wait until another PR is approved, push latest
> updates to your branch and then I will review it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HackYourFuture-CPH/class-25-lothbrok/pull/4#issuecomment-1727172243>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ56IXCL6CLGTMIZQTUKZK3X3KOSDANCNFSM6AAAAAA46ZF56M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-23 15:44 UTC, YurijPaharev commented on frontend/src/App.tsx
> -          <Route path="/login" element={<LoginPage />} />
Excuse me, but why are you deleting the App.tsx file?

2023-09-25 09:43 UTC, YurijPaharev approved these changes

2023-09-25 16:05 UTC, merged